function PlayerCard() {
  return {
    charTokenFilename: charTokenFilename,
    charName: charName,
    charRace: charRace,
    charAge: charAge,
    charAlignment: charAlignment,
    charBelief: charBelief,
    charJob: setCharJobs(charJobs),
    charAttName: ["力量", "敏捷", "体质", "智力", "感知", "魅力"],
    charAttValue: charAttValue,
    charAttModifier: charAttModifier,
    charAC: setCharAC(charACInfos),
    charSpeed: charSpeed,
    charFlyType: charFlyType,
    charSavingThrows: charSavingThrows,
    charBAB: charBAB,
    charCMB: charCMB,
    charCMD: charCMD,
    charHP: charHP,
    charInitiative: charInitiative,
    charAB: charAB,
    charSR: charSR,
    charLanguage: charLanguage,
    charSpecial: charSpecial,
    charSpellLike: charSpellLike,
    charFeats: charFeats,
    charSpells: charSpells,
    charSkillTotalPoints: setSkillsTotalPoints(charJobs, "int"),
    charSkillUsedPoints: setAllUsedSkillsPoints(charSkills),
    charSkills: charSkills,
    charBattleOptions: charBattleOptions,
  };
}
